[versions]
kotlin = "2.3.0"
compose = "1.9.3"
coroutines = "1.10.2"
xml = "0.91.3"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-html-core = { module = "org.jetbrains.compose.html:html-core", version.ref = "compose" }
compose-html-svg = { module = "org.jetbrains.compose.html:html-svg", version.ref = "compose" }
compose-html-testUtils = { module = "org.jetbrains.compose.html:html-test-utils", version.ref = "compose" }

serialization-xml = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xml" }
serialization-corejdk = { module = "io.github.pdvrieze.xmlutil:core-jdk", version.ref = "xml" }

[plugins]
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
licensee = { id = "app.cash.licensee", version = "1.14.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
mavencentral = { id = "io.github.hfhbd.mavencentral", version = "0.0.23" }
